
tasks:
  - name: "Run the container"
    command: docker run --name yottadb --entrypoint /home/luacode/entrypoint.sh -it -v $PWD/code:/home/luacode docker.io/yottadb/yottadb-base

  - name: "Run YottaDB prompt"
    command:  sleep 60 && docker exec -it yottadb /opt/yottadb/current/ydb
    openMode: split-right

  - name: "Run Lua"
    command:  sleep 60 && docker exec -it yottadb lua
    openMode: split-right


